### ISSUE TITLE
Development build failing on django-openid-provider==0.6

### ISSUE THREAD

**Issue by skaven81** [astrobin/astrobin#596]
The backend container (`astrobin.dockerfile`) is failing to build one of its requirements.  This is from a completely bare-bones from-scratch build (using `--no-cache` and without any pre-existing state)

```
Collecting django-openid-provider==0.6 (from -r requirements.txt (line 63))
  Downloading django_openid_provider-0.6.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/django_openid_provider.egg-info
    writing pip-egg-info/django_openid_provider.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vlcwQG/django-openid-provider/setup.py", line 23, in <module>
        "Framework :: Django",
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python2.7/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 76, in write_pkg_file
        file.write('%s: %s\n' % (field, attr_val))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u0144' in position 20: ordinal not in range(128)
```

**Comment by skaven81** [comment]
@siovene are you seeing this on new builds?  I'll keep poking at it...

**Comment by skaven81** [comment]
going back to an older commit does not fix the issue, so chances are it's upstream...

**Comment by siovene** [comment]
The last nightly build worked: https://travis-ci.org/astrobin/astrobin/builds/354429136

Probably a temporary issue on the PyPy repository.

**Comment by skaven81** [comment]
Looks like that fixes it -- I'll submit a PR shortly after a full test.

**Comment by skaven81** [comment]
Crap...it's spreading!

```
Collecting django-bootstrap-breadcrumbs==0.8.2 (from -r requirements.txt (line 34))
  Downloading django_bootstrap_breadcrumbs-0.8.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/django_bootstrap_breadcrumbs.egg-info
    writing requirements to pip-egg-info/django_bootstrap_breadcrumbs.egg-info/requires.txt
    writing pip-egg-info/django_bootstrap_breadcrumbs.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lezqdI/django-bootstrap-breadcrumbs/setup.py", line 37, in <module>
        include_package_data=True,
      File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 271, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/local/lib/python2.7/dist-packages/setuptools/command/egg_info.py", line 604, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python2.7/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 76, in write_pkg_file
        file.write('%s: %s\n' % (field, attr_val))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u0141' in position 8: ordinal not in range(128)
```

**Comment by siovene** [comment]
Then it's definitely the repository acting up.

**Comment by skaven81** [comment]
possibly related: https://github.com/pypa/setuptools/issues/984

**Comment by skaven81** [comment]
Opened #597 to fix this
